"""Write requirements/bundle.lock from the installed runtime graph.

ARCHITECTURE_V1.md §6.2: bundles rebuild from a lock file. This script
records the versions actually installed in the current environment for the
direct runtime packages and their dependencies. It does not fetch from the
network.
"""

from __future__ import annotations

import argparse
import re
from importlib.metadata import PackageNotFoundError, distribution, requires
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIRECT = [
    "numpy",
    "scipy",
    "soundfile",
    "sounddevice",
    "matplotlib",
    "PySide6_Essentials",
    "shiboken6",
]


def _requirement_name(entry: str) -> str | None:
    item = entry.split(";")[0].strip()
    if not item or item.startswith("#"):
        return None
    # The PEP 508 name, whatever follows it ("~=4.0", "===1", "@ url", "(>=1)").
    match = re.match(r"[A-Za-z0-9][A-Za-z0-9._-]*", item)
    return match.group(0) if match else None


def _walk(name: str, seen: dict[str, str]) -> None:
    key = name.lower().replace("_", "-")
    if key in seen:
        return
    try:
        dist = distribution(name)
    except PackageNotFoundError:
        return
    seen[key] = f"{dist.metadata['Name']}=={dist.version}"
    for extra in requires(name) or []:
        # Only the marker: "foo-extra==1.0" is a dependency, not an extra.
        _requirement, _sep, marker = extra.partition(";")
        if re.search(r"\bextra\s*==", marker):
            continue
        child = _requirement_name(extra)
        if child:
            _walk(child, seen)


def _installed(name: str) -> bool:
    try:
        distribution(name)
    except PackageNotFoundError:
        return False
    return True


def compile_lock() -> list[str]:
    seen: dict[str, str] = {}
    for name in DIRECT:
        _walk(name, seen)
    return [seen[key] for key in sorted(seen)]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=ROOT / "requirements" / "bundle.lock",
        help="lock file to write",
    )
    args = parser.parse_args(argv)
    # A lock without one of them would leave that package unpinned in the bundle.
    missing = [name for name in DIRECT if not _installed(name)]
    if missing:
        raise SystemExit(
            f"not installed: {', '.join(missing)}; install the bundle's runtime "
            'packages (pip install -e ".[gui]") first'
        )
    lines = compile_lock()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Generated by scripts/compile_bundle_lock.py from the current environment.\n"
        "# Rebuild a bundle from this file. Do not edit by hand.\n"
    )
    args.out.write_text(header + "\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {args.out} ({len(lines)} packages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
