"""Write requirements/bundle.lock from the installed runtime graph.

ARCHITECTURE_V1.md §6.2: bundles rebuild from a lock file. This script
records the versions actually installed in the current environment for the
direct runtime packages and their dependencies. It does not fetch from the
network.
"""

from __future__ import annotations

import argparse
from importlib.metadata import PackageNotFoundError, distribution, requires
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIRECT = [
    "numpy",
    "scipy",
    "soundfile",
    "sounddevice",
    "matplotlib",
    "PySide6_Essentials",
    "shiboken6",
]


def _requirement_name(entry: str) -> str | None:
    item = entry.split(";")[0].strip()
    if not item or item.startswith("#"):
        return None
    for separator in ("[", " ", "<", ">", "=", "!"):
        if separator in item:
            item = item.split(separator, 1)[0]
    return item.strip() or None


def _walk(name: str, seen: dict[str, str]) -> None:
    key = name.lower().replace("_", "-")
    if key in seen:
        return
    try:
        dist = distribution(name)
    except PackageNotFoundError:
        return
    seen[key] = f"{dist.metadata['Name']}=={dist.version}"
    for extra in requires(name) or []:
        if "extra ==" in extra:
            continue
        child = _requirement_name(extra)
        if child:
            _walk(child, seen)


def compile_lock() -> list[str]:
    seen: dict[str, str] = {}
    for name in DIRECT:
        _walk(name, seen)
    return [seen[key] for key in sorted(seen)]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=ROOT / "requirements" / "bundle.lock",
        help="lock file to write",
    )
    args = parser.parse_args(argv)
    lines = compile_lock()
    if not lines:
        raise SystemExit("no installed runtime packages found")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Generated by scripts/compile_bundle_lock.py from the current environment.\n"
        "# Rebuild a bundle from this file. Do not edit by hand.\n"
    )
    args.out.write_text(header + "\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {args.out} ({len(lines)} packages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
